using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.UserInterface.CustomControls
{
    /// <summary>
    ///     Any UI that takes up the entire screen.
    /// </summary>
    [GenerateTypedNameReferences]
    [Virtual]
    public partial class DefaultFullscreen : BaseFullscreen
    {
        public DefaultFullscreen()
        {
            RobustXamlLoader.Load(this);
            MouseFilter = MouseFilterMode.Stop;

            Contents = ContentsContainer;

            XamlChildren = new ContentCollection<Control>(this.Contents);
        }

        public Control Contents { get; private set; }
    }
}
